# Generated by Django 4.1.1 on 2022-09-18 13:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.basemodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("blog.basemodel",),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.basemodel",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_picture", models.URLField(max_length=500)),
                ("bio", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "account_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.account"
                    ),
                ),
            ],
            bases=("blog.basemodel",),
        ),
        migrations.CreateModel(
            name="ProfileFollowOthers",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.basemodel",
                    ),
                ),
                (
                    "followed_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followed_profile",
                        to="blog.profile",
                    ),
                ),
                (
                    "profile_which_follow_other",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_which_follow_other",
                        to="blog.profile",
                    ),
                ),
            ],
            bases=("blog.basemodel",),
        ),
        migrations.CreateModel(
            name="OthersFollowProfile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.basemodel",
                    ),
                ),
                (
                    "following_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="following_profile",
                        to="blog.profile",
                    ),
                ),
                (
                    "profile_which_gets_followed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_which_gets_followed",
                        to="blog.profile",
                    ),
                ),
            ],
            bases=("blog.basemodel",),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.basemodel",
                    ),
                ),
                (
                    "liked_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.profile",
                    ),
                ),
            ],
            bases=("blog.basemodel",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.basemodel",
                    ),
                ),
                ("blog_text", models.CharField(default="", max_length=100)),
                (
                    "blog_image",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500), size=5
                    ),
                ),
                (
                    "blog_like",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.like",
                    ),
                ),
                (
                    "blog_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.profile"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
                    ),
                ),
            ],
            bases=("blog.basemodel",),
        ),
    ]
